name: Deploy 2048 Game to AWS ECS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  ECS_SERVICE: ${{ secrets.ECS_SERVICE }}
  ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
  ECS_TASK_DEFINITION: ${{ secrets.ECS_TASK_DEFINITION }}
  CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
  TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}
  TF_VAR_subdomain: ${{ secrets.SUBDOMAIN }}
  TF_VAR_vpc_id: ${{ secrets.VPC_ID }}
  TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Run tests
      run: |
        echo "Running tests..."
        npm test
        echo "Tests completed successfully"

  infrastructure:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    outputs:
      ecr_repository_url: ${{ steps.terraform.outputs.ecr_repository_url }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Debug Environment Variables
      run: |
        echo "AWS_REGION: us-east-1"
        echo "ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}"
        echo "ECS_SERVICE: ${{ secrets.ECS_SERVICE }}"
        echo "ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}"
        echo "DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}"
        echo "SUBDOMAIN: ${{ secrets.SUBDOMAIN }}"
        echo "VPC_ID: ${{ secrets.VPC_ID }}"
        echo "AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Terraform Init
      run: |
        echo "Initializing Terraform..."
        terraform init
        echo "Terraform initialized successfully"
      working-directory: ./terraform

    - name: Terraform Plan
      run: |
        echo "Planning Terraform deployment..."
        terraform plan -detailed-exitcode
        echo "Terraform plan completed"
      working-directory: ./terraform

    - name: Terraform Apply
      id: terraform
      run: |
        echo "Applying Terraform configuration..."
        terraform apply -auto-approve
        echo "Terraform apply completed"
        echo "Getting ECR repository URL..."
        ECR_URL=$(terraform output -raw ecr_repository_url)
        echo "ECR URL: $ECR_URL"
        echo "ecr_repository_url=$ECR_URL" >> $GITHUB_OUTPUT
      working-directory: ./terraform

  build-and-deploy:
    needs: infrastructure
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        echo "Building Docker image..."
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        echo "Docker image built successfully"
        echo "Pushing image to ECR..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "Image pushed successfully"
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Substitute environment variables in task definition
      run: |
        echo "Substituting environment variables in task definition..."
        echo "AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID"
        echo "AWS_REGION: $AWS_REGION"
        envsubst < task-definition.json > task-definition-final.json
        echo "Task definition updated:"
        cat task-definition-final.json
      env:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        AWS_REGION: ${{ env.AWS_REGION }}

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition-final.json
        container-name: ${{ env.CONTAINER_NAME }}
        image: ${{ steps.build-image.outputs.image }}

    - name: Deploy Amazon ECS task definition
      run: |
        echo "Deploying to ECS..."
        echo "Service: ${{ env.ECS_SERVICE }}"
        echo "Cluster: ${{ env.ECS_CLUSTER }}"
      
    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true