name: Deploy 2048 Game to AWS ECS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  ECS_SERVICE: ${{ secrets.ECS_SERVICE }}
  ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
  ECS_TASK_DEFINITION: ${{ secrets.ECS_TASK_DEFINITION }}
  CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
  TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}
  TF_VAR_subdomain: ${{ secrets.SUBDOMAIN }}
  TF_VAR_vpc_id: ${{ secrets.VPC_ID }}
  TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Run tests
      run: |
        echo "Running tests..."
        npm test
        echo "Tests completed successfully"

  infrastructure:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    outputs:
      ecr_repository_url: ${{ steps.terraform.outputs.ecr_repository_url }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Debug Environment Variables
      run: |
        echo "AWS_REGION: us-east-1"
        echo "ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}"
        echo "ECS_SERVICE: ${{ secrets.ECS_SERVICE }}"
        echo "ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}"
        echo "DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}"
        echo "SUBDOMAIN: ${{ secrets.SUBDOMAIN }}"
        echo "VPC_ID: ${{ secrets.VPC_ID }}"
        echo "AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Debug Terraform Variables
      run: |
        echo "=== Terraform Variables ==="
        echo "TF_VAR_aws_region: $TF_VAR_aws_region"
        echo "TF_VAR_domain_name: $TF_VAR_domain_name"
        echo "TF_VAR_subdomain: $TF_VAR_subdomain"
        echo "TF_VAR_vpc_id: $TF_VAR_vpc_id"
        echo "TF_VAR_aws_account_id: $TF_VAR_aws_account_id"
        echo "Working directory: $(pwd)"
        echo "Terraform files:"
        ls -la ./terraform/
      env:
        TF_VAR_aws_region: us-east-1
        TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}
        TF_VAR_subdomain: ${{ secrets.SUBDOMAIN }}
        TF_VAR_vpc_id: ${{ secrets.VPC_ID }}
        TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}

    - name: Terraform Init
      run: |
        echo "=== Terraform Init ==="
        echo "Initializing Terraform..."
        terraform init -no-color
        echo "Terraform initialized successfully"
        echo "Terraform version:"
        terraform version
      working-directory: ./terraform
      env:
        TF_VAR_aws_region: us-east-1
        TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}
        TF_VAR_subdomain: ${{ secrets.SUBDOMAIN }}
        TF_VAR_vpc_id: ${{ secrets.VPC_ID }}
        TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}

    - name: Terraform Validate
      run: |
        echo "=== Terraform Validate ==="
        terraform validate -no-color
        echo "Terraform validation completed"
      working-directory: ./terraform
      env:
        TF_VAR_aws_region: us-east-1
        TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}
        TF_VAR_subdomain: ${{ secrets.SUBDOMAIN }}
        TF_VAR_vpc_id: ${{ secrets.VPC_ID }}
        TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}

    - name: Terraform Plan
      run: |
        echo "=== Terraform Plan ==="
        echo "Planning Terraform deployment..."
        terraform plan -no-color -detailed-exitcode -out=tfplan
        echo "Terraform plan completed"
        echo "Plan summary:"
        terraform show -no-color tfplan
      working-directory: ./terraform
      env:
        TF_VAR_aws_region: us-east-1
        TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}
        TF_VAR_subdomain: ${{ secrets.SUBDOMAIN }}
        TF_VAR_vpc_id: ${{ secrets.VPC_ID }}
        TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}

    - name: Terraform Apply
      id: terraform
      run: |
        echo "=== Terraform Apply ==="
        echo "Applying Terraform configuration..."
        terraform apply -no-color -auto-approve tfplan
        echo "Terraform apply completed"
        echo "Getting outputs..."
        terraform output -no-color
        echo "Getting ECR repository URL..."
        ECR_URL=$(terraform output -raw ecr_repository_url)
        echo "ECR URL: $ECR_URL"
        echo "ecr_repository_url=$ECR_URL" >> $GITHUB_OUTPUT
      working-directory: ./terraform
      env:
        TF_VAR_aws_region: us-east-1
        TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}
        TF_VAR_subdomain: ${{ secrets.SUBDOMAIN }}
        TF_VAR_vpc_id: ${{ secrets.VPC_ID }}
        TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}

  build-and-deploy:
    needs: infrastructure
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Debug Build Environment
      run: |
        echo "=== Build Environment ==="
        echo "ECR_REPOSITORY: $ECR_REPOSITORY"
        echo "ECS_SERVICE: $ECS_SERVICE"
        echo "ECS_CLUSTER: $ECS_CLUSTER"
        echo "CONTAINER_NAME: $CONTAINER_NAME"
        echo "AWS_REGION: $AWS_REGION"
        echo "Current directory: $(pwd)"
        echo "Docker files:"
        ls -la

    - name: Login to Amazon ECR
      id: login-ecr
      run: |
        echo "=== ECR Login ==="
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com
        echo "ECR login successful"

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
        IMAGE_TAG: ${{ github.sha }}
      run: |
        echo "=== Docker Build & Push ==="
        echo "Building Docker image..."
        echo "Registry: $ECR_REGISTRY"
        echo "Repository: $ECR_REPOSITORY"
        echo "Tag: $IMAGE_TAG"
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        echo "Docker image built successfully"
        echo "Pushing image to ECR..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "Image pushed successfully"
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Substitute environment variables in task definition
      run: |
        echo "=== Task Definition Substitution ==="
        echo "Substituting environment variables in task definition..."
        echo "AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID"
        echo "AWS_REGION: $AWS_REGION"
        echo "Original task definition:"
        cat task-definition.json
        envsubst < task-definition.json > task-definition-final.json
        echo "Updated task definition:"
        cat task-definition-final.json
      env:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        AWS_REGION: us-east-1

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      run: |
        echo "=== ECS Task Definition Render ==="
        echo "Container name: ${{ env.CONTAINER_NAME }}"
        echo "Image: ${{ steps.build-image.outputs.image }}"
      
    - name: Render ECS Task Definition
      id: task-def-render
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition-final.json
        container-name: ${{ env.CONTAINER_NAME }}
        image: ${{ steps.build-image.outputs.image }}

    - name: Deploy Amazon ECS task definition
      run: |
        echo "=== ECS Deployment ==="
        echo "Deploying to ECS..."
        echo "Service: ${{ env.ECS_SERVICE }}"
        echo "Cluster: ${{ env.ECS_CLUSTER }}"
        echo "Task definition: ${{ steps.task-def-render.outputs.task-definition }}"
      
    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def-render.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true